### ISSUE TITLE
Sheet 2 - All Regulators

### ISSUE THREAD

**Issue by aoberste** [JasMoH/Photoacoustic#2]
Inductors typically aren't required on the inputs/outputs of linear regulators.  The datasheets do not call for them.  I would be wary of including these without simulating, could affect stability.  The linear regulators in use already have noise levels in the uV range, there isn't much benefit to be gained from further filtering.

**Comment by JasMoH** [comment]
Marked DNI/0 ohm jumpers, leaving footprint on for now in case I need to tweak.

Pull off of version 2 if unused.
