### ISSUE TITLE
RF Split

### ISSUE THREAD

**Issue by aoberste** [JasMoH/Photoacoustic#5]
On sheet 3, it looks like you are splitting an RF input into two demodulators by simply "tee-ing" the trace, or tapping along the way.  This will cause issue.  Research a Wilkinson divider, it can generally be implemented with a few passives.

**Comment by JasMoH** [comment]
I'm targeting sub 10 MHz for an initial design, and I'm honestly expecting to be sub 100 kHz for most of it. That's analog, not digital clock rate, so I'm not super concerned with harmonics. 

Thanks for the tip though, that's a great design, and I have a soft spot for distributed microwave circuitry.
